### ISSUE TITLE
Observables  Context??

### ISSUE THREAD

**Issue by trinadhkoya** [kaushikgopal/RxJava-Android-Samples#106]
Hi Kaushik,
It would be great if you can help with Observables,like
Which observable ,i can make use of when i was dealing with AsyncTask
and Which Observable I can make use of Login and SignUP and 
Difference between and Disposable and Composite Disposable?

**Comment by kaushikgopal** [comment]
hey @trinadhkoya. I would love to help, but I imagine something like StackOverflow/blog post/Twitter is the better platform for those specific questions.

The [description](https://github.com/kaushikgopal/RxJava-Android-Samples#description) in the readme talks of some of the use cases (like AsyncTasks etc.) which should be helpful in guiding that decision (to an extent),
