### ISSUE TITLE
Exceeds Dex Limit of 64k in its current state.

### ISSUE THREAD

**Issue by barykaed** [kaushikgopal/RxJava-Android-Samples#108]
I just cloned the repo and tried to build
```
./gradlew clean assemble  
```
The build fails with the following error:
```
Dex: The number of method references in a .dex file cannot exceed 64K.
```
Is this a known issue? I can try and submit a pull request to fix this soon. I just wanted to check before a pull request.

**Comment by kaushikgopal** [comment]
✌️ merged PR. Thanks for this
