### ISSUE TITLE
[Question] Help Needed

### ISSUE THREAD

**Issue by nksaroj** [kaushikgopal/RxJava-Android-Samples#110]
Polling to Backend API in regular interval for certain number of times in a regular interval - Retrofit & RxJava

https://stackoverflow.com/questions/44920829/polling-to-backend-api-in-regular-interval-for-certain-number-of-times-in-a-regu

**Comment by kaushikgopal** [comment]
@nksaroj - great to see you got answers on SO. Also added a third option there for "short-circuiting" observables that I've found nifty in the past.
