### ISSUE TITLE
Update samples to reflect version1.0.+ (widget etc. package removed)

### ISSUE THREAD

**Issue by morphine9** [kaushikgopal/RxJava-Android-Samples#21]

**Comment by yudhir** [comment]
version 1.0 doesn't have widgets etc , Why did they break support for 0.25?

**Comment by kaushikgopal** [comment]
i could have sworn i updated the code to reflect this. it appears i didn't push the changes duh! will make the changes and push up the updated code.

@yudhir : i think it's a move in the right direction. for the widget bindings stuff there's RxBindings. I'll update the code here to reflect those changes.

For more reading and insight:

1. [Issue #172 on RxAndroid](https://github.com/ReactiveX/RxAndroid/issues/172)
2. [Dan Lew's post](http://blog.danlew.net/2015/09/01/how-to-upgrade-to-rxandroid-10/)
