### ISSUE TITLE
String is van empty or null

### ISSUE THREAD

**Issue by BenGroot** [kaushikgopal/RxJava-Android-Samples#22]
Hi Kaushik,

I like your example of the form validation, thanks for that! 

Is there a reason why you use the
com.google.common.base.Strings.isNullOrEmpty instead of the TextUtils.isEmpty() in there?

**Comment by kaushikgopal** [comment]
laziness and legacy code :)

thanks for pointing it out. i should totally get rid of it. that would additionally help me get rid of the guava dependency.
