### ISSUE TITLE
Observing a single Observable in multiple fragments/activities

### ISSUE THREAD

**Issue by wKovacs64** [kaushikgopal/RxJava-Android-Samples#23]
To observe the same `Observable` (results of a Retrofit call, for example) in multiple fragments or activities, is it normal to subscribe to the `Observable` in the same scope where it exists (retained fragment, singleton, whatever) in order to keep the calls from terminating (e.g. chained network calls with `flatMap()`) and create a new `Subscription` to the `Observable` in each interested fragment/activity? Or is there a better approach?

**Comment by kaushikgopal** [comment]
Based on current experience, I do what you suggest as an option i.e. create a new `Subscription` for each interested fragment/activity. I feel that's more "idiomatic" as it relegates the responsibility of how to react to the event, down to the interested parties.

(Note: your `Observable` however must be `share`able especially for something like a retrofit call, lest creating new `Subscription`s everywere would restart same network calls. I'm guessing you already knew that but doesn't hurt to reiterate :))

**Comment by wKovacs64** [comment]
Cool, thanks for the reassurance.
