### ISSUE TITLE
Double binding TextView demo also can be implemented with combineLatest

### ISSUE THREAD

**Issue by ltn614** [kaushikgopal/RxJava-Android-Samples#31]
I think Double binding TextView demo also can be implemented with combineLatest operator

**Comment by kaushikgopal** [comment]
the problem with `combineLatest` is that it needs *all* inputs to kick off the input. What this means is that if you change one value, your output doesn't change until the second input also has a value provided. This is not entirely favorable in the double binding scenarios. 

If you still feel there's an elegant way out, feel free to open this issue.

**Comment by ltn614** [comment]
You are right about, I didn't thought that problem, great work by the way, helps me a lot.
