### ISSUE TITLE
I'm very interested in paging. 

### ISSUE THREAD

**Issue by Rainer-Lang** [kaushikgopal/RxJava-Android-Samples#32]

**Comment by polok** [comment]
Have a look into this example : https://github.com/matzuk/PaginationSample

**Comment by kaushikgopal** [comment]
i've been toying with this. i'm trying to come up with an example/idea that demonstrates the pagination action purely through Rx. linked project is pretty nifty, but relies (from a quick perusal) on the recycling nature of the recycler-view). let me try to cook something up too.

**Comment by zhoul-HS** [comment]
I really liked (and am using a version of) Matthias Käppler's Rx pager gist: https://gist.github.com/mttkay/24881a0ce986f6ec4b4d

But you need a very solid grasp of the used operators to understand how it works (aka confusing for beginners)

**Comment by kaushikgopal** [comment]
that's super sweet. never come across that before. will definitely take a peek for inspiration :)

**Comment by kaushikgopal** [comment]
added a simple pagination example https://github.com/kaushikgopal/RxJava-Android-Samples#pagination

**Comment by nabeelpkl** [comment]
@kaushikgopal I am a beginner to Rxjava. I checked your example for pagination and couldn't understand it clearly. Would like to know how you handle errors when server returns some.  I got `io.reactivex.exceptions.OnErrorNotImplementedException:` while implementing your example. please help me.
