### ISSUE TITLE
Wiki Pages for examples

### ISSUE THREAD

**Issue by marukami** [kaushikgopal/RxJava-Android-Samples#49]
Do you think that having github wiki page for each example would help people new to Rx understand the examples better? I'm thinking something like [Code Path](https://github.com/codepath/android_guides/wiki ). Then we could use resource like http://rxmarbles.com/ to help visualize the example.

**Comment by kaushikgopal** [comment]
Hmm... I like the idea of the wiki but do you think it would give any additional value besides the `README`?

If i remember correctly, github wikis have to be maintained independently and at that point I really don't see the value if it's a more flushed out README.

One of my initial ideas was to change all the existing "log" statements in the examples to a visualization. I almost started a similar `RxJs` repository to whip up the examples but life got in the way :P. 

The other trouble (from my early memories of trying to come up with something like RxMarbles pre rxmarbles.com) was that the boilerplate to set it up was not non-trivial. There was enough anciliary code that it actually made the examples harder to understand, which i'm definitely against. The point of the repo was always to make it super simple to just see the code and understand how Rx achieves the examples.

**Comment by marukami** [comment]
I think your right. I will suggest linking to the examples from the `README`, you already refer to the PseudoCacheMergeFragment without a link. 

Thanks for the feedback. I think what I will do is setup another repo similar to how Code Path work and use the examples as resources for tutorials. That way I can also include multiple languages and platforms. especially since I'm working on some C# and F# examples.
