### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by yarivkenan** [kaushikgopal/RxJava-Android-Samples#61]
2. [DebouncedBuffer used for the fancier variant of the demo](http://nerds.weddingpartyapp.com/tech/2014/12/24/secret-bonus-part-debouncedbuffer-used-in-rxbus-example/)
doesn't work

**Comment by kaushikgopal** [comment]
🙏  thanks for pointing that out. I fixed the links and pointed to versions of the post that should now hopefully be permanent. The formatting may not yet be upto snuff, but the content should be there.

Btw that post is 👉  http://blog.kaush.co/2015/01/05/debouncedbuffer-with-rxjava/
