### ISSUE TITLE
CacheMerge example updates entire adapter for each onNext

### ISSUE THREAD

**Issue by JimVercoelen** [kaushikgopal/RxJava-Android-Samples#72]
Hi,

Was checking out this repo (which is awesome btw) 
and noticed that the CacheMerge example does some unnecessary updating (I think).

For each onNext() the entire adapter will be cleared and updated,
while there is only added one 'contributor' at a time.

This looks a bit inefficiently to me.

`@Override`
`public void onNext(Pair<Contributor, Long> contributorAgePair) {`
`...`
`_adapter.clear();`
`_adapter.addAll(getListStringFromMap());`
`}`

Only adding the 'Next' 'contributor' could be better or not?
`@Override`
`public void onNext(Pair<Contributor, Long> contributorAgePair) {`
`...`
`String rowLog = String.format("%s [%d]", contributor.login, contributor.contributions);`
`_adapter.add(rowLog);`
`}`

**Comment by JimVercoelen** [comment]
I added an pull request in case It could be better

**Comment by kaushikgopal** [comment]
thanks @JimVercoelen I've added some comments on #73. Let's carry the conversation there. Closing this issue out.
