### ISSUE TITLE
Enhanced RxBus

### ISSUE THREAD

**Issue by djodjoni** [kaushikgopal/RxJava-Android-Samples#75]
Nice repo! Also really simple and easy approach to achieve Pub-Sub pattern in RxBus.

would you consider enhancing the example with smth like https://github.com/apptik/rxHub ?
I would be more than happy to provide a PR.

**Comment by kaushikgopal** [comment]
hey @djodjoni ! thanks for the pointer. honestly, i want to keep this examples as lean and crazy simple as possible. rxHub looks pretty cool but i want to stick with a drop dead Subject for this example (just so everyone understand the working better)

Cheers and thanks!
