### ISSUE TITLE
After value change -> execute once

### ISSUE THREAD

**Issue by Rainer-Lang** [kaushikgopal/RxJava-Android-Samples#78]
After getting a specfic value from an Observable, I would like to execute a method only once. -> on Completed()

How could this be possible?

**Comment by WassimBenltaief** [comment]
You can use one of the doOnX methods :

doOnNext()
doOnCompleted()
doOnError()
doOnEach()

In your case it's doOnCompleted() :

![Marble diagram](http://reactivex.io/documentation/operators/images/doOnCompleted.png)

**Comment by Rainer-Lang** [comment]
@WassimBenltaief So I should complete/end the stream and make within doOnCompleted my method call?

**Comment by WassimBenltaief** [comment]
If you want to execute the methode once the stream ends succesfully, so doOnCompleted is the right place. If your expected value is in the middle of the stream so doOnNext with a check inside is the appropriate.

examples :

**Comment by kaushikgopal** [comment]
@Rainer-Lang @WassimBenltaief is 💯 right. 

executing a single method can be done in many ways. it depends at which point you want the single method to be executed. in all likelihood you would use a variant of the `doOnX` as suggested.

Have a look at the repository to see the different ways [`doOnNext` is used](https://github.com/kaushikgopal/RxJava-Android-Samples/search?utf8=✓&q=doOnNext&type=Code)  or [`doOnSubscribe`](https://github.com/kaushikgopal/RxJava-Android-Samples/search?utf8=✓&q=doOnSubscribe&type=Code) etc.

I'm closing this issue as it has nothing to do with the examples in this repo.

**Comment by Rainer-Lang** [comment]
@kaushikgopal It wasn't executing a method. It was about executing a method after a change of an Observable to a specific value and THAN execute a method only once and finish.
But you're right, @WassimBenltaief gave me a hint.
BUT, maybe this could be also something for your repo. ;)
