### ISSUE TITLE
RxJava 1 branch

### ISSUE THREAD

**Issue by aldoKelvianto** [kaushikgopal/RxJava-Android-Samples#91]
There's still plenty of RxJava users who haven't migrated to RxJava 2, please provide RxJava 1 branch. Sure you can checkout to #e200ab but I think it would be easier just to switch a dedicated branch.

**Comment by kaushikgopal** [comment]
fair point.

Created an [RxJava 1 branch](https://github.com/kaushikgopal/RxJava-Android-Samples/tree/feat/rxjava_1)
