### ISSUE TITLE
Have you stopped maintaining this project?

### ISSUE THREAD

**Issue by qazt482** [kaushikgopal/RxJava-Android-Samples#92]
Seems multiple PRs oustanding.

**Comment by kaushikgopal** [comment]
You'll notice the last commit was 22 days ago. So nope :). Still under maintenance. The outstanding PRS are ones where we haven't come to a conclusion yet. But don't hinder the current working of the repo anyway.  

But you're right I should pin em down and come to some conclusion. I'll try to get to em these holidays. 

Were you looking for anything specifically ?
