### ISSUE TITLE
GUI elements must not be accessed from non-main threads

### ISSUE THREAD

**Issue by tmtron** [kaushikgopal/RxJava-Android-Samples#94]
As far as I understand the following code from [DebounceSearchEmitterFragment.java#L76](https://github.com/kaushikgopal/RxJava-Android-Samples/blob/master/app/src/main/java/com/morihacky/android/rxjava/fragments/DebounceSearchEmitterFragment.java#L76):
```java
_disposable = RxJavaInterop.toV2Observable(RxTextView.textChangeEvents(_inputSearchText))
              .debounce(400, TimeUnit.MILLISECONDS)// default Scheduler is Computation
              .filter(changes -> isNotNullOrEmpty(_inputSearchText.getText().toString()))
              .observeOn(AndroidSchedulers.mainThread())
              .subscribeWith(_getSearchObserver());
```
`filter()` accesses the GUI element `_inputSearchText`, which it must not do: see [StackOverflow: Is it okay to read data from UI elements in another thread?](http://stackoverflow.com/questions/40044213/is-it-okay-to-read-data-from-ui-elements-in-another-thread)

Instead the text should be read from the change-event like this:
`.filter(changes -> isNotNullOrEmpty(changes.text().toString()))`

**Comment by kaushikgopal** [comment]
great catch! do you feel like submitting a mini-PR instead :) ? i'm happy to make the change, but would like to attribute the credit to you.
