### ISSUE TITLE
You are using a private api (as of support library v25 and up)

### ISSUE THREAD

**Issue by ber4444** [kaushikgopal/RxJava-Android-Samples#97]
Meaning getFragments at https://github.com/kaushikgopal/RxJava-Android-Samples/blob/master/app/src/main/java/com/morihacky/android/rxjava/fragments/RotationPersist2WorkerFragment.java
Also asked about it at http://stackoverflow.com/questions/41969694/

**Comment by kaushikgopal** [comment]
🙏 thanks for the report
